# Generated by Django 5.1.6 on 2025-03-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_pedido_purchase_purchaseitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='price',
            new_name='total_price',
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
