# Generated by Django 5.1.6 on 2025-03-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_purchase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
