# Generated by Django 5.1.6 on 2025-03-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_purchaseitem_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pendiente', 'Enviado')], default='Pendiente', max_length=20),
        ),
    ]
